"""Pipeline-generated tool modules.

Tools in this package are immutable source files generated by the unified pipeline.
The runtime imports them at startup and has no APIs to modify them.
"""

from .manifest import load_manifest, ToolManifest

__all__ = ["load_manifest", "ToolManifest"]
