"""Auto-generated tool module."""

from __future__ import annotations

import json


def run(payload: str) -> str:
    import json
    from datetime import datetime, timezone
    try:
        data = json.loads(payload)
        start = data.get('start_date')
        end = data.get('end_date')
        if not start or not end:
            return json.dumps({'error': 'start_date and end_date are required'}, ensure_ascii=False)
        # Simulate reading from an audit log; in production this would query a database
        mock_log = [
            {'timestamp': '2025-03-01T08:30:00Z', 'level': 'INFO', 'user': 'alice', 'event': 'LOGIN', 'message': 'User alice logged in from IP 192.168.1.10'},
            {'timestamp': '2025-03-01T09:15:00Z', 'level': 'WARN', 'user': 'bob', 'event': 'TRANSACTION_CREATE', 'message': 'Large transfer of 50000.00 USD initiated, requires approval'},
            {'timestamp': '2025-03-01T10:00:00Z', 'level': 'ERROR', 'user': 'system', 'event': 'SYSTEM_EVENT', 'message': 'Database connection timeout, retrying'},
            {'timestamp': '2025-03-01T11:20:00Z', 'level': 'CRITICAL', 'user': 'charlie', 'event': 'ACCOUNT_MODIFY', 'message': 'Unauthorized attempt to modify account 12345, blocked'},
            {'timestamp': '2025-03-01T12:00:00Z', 'level': 'INFO', 'user': 'alice', 'event': 'REPORT_GENERATE', 'message': 'Monthly financial report generated by alice'}
        ]
        filtered = []
        for entry in mock_log:
            entry_time = datetime.fromisoformat(entry['timestamp'].replace('Z', '+00:00'))
            start_dt = datetime.fromisoformat(start.replace('Z', '+00:00')) if 'Z' in start else datetime.fromisoformat(start)
            end_dt = datetime.fromisoformat(end.replace('Z', '+00:00')) if 'Z' in end else datetime.fromisoformat(end)
            if entry_time < start_dt or entry_time > end_dt:
                continue
            if 'log_level' in data and data['log_level'] and entry['level'] != data['log_level']:
                continue
            if 'user_id' in data and data['user_id'] and entry['user'] != data['user_id']:
                continue
            if 'event_type' in data and data['event_type'] and entry['event'] != data['event_type']:
                continue
            if 'search_text' in data and data['search_text']:
                if data['search_text'].lower() not in entry['message'].lower():
                    continue
            filtered.append(entry)
        max_results = data.get('max_results', 100)
        filtered = filtered[:max_results]
        return json.dumps({'entries': filtered, 'count': len(filtered)}, ensure_ascii=False)
    except Exception as e:
        return json.dumps({'error': str(e)}, ensure_ascii=False)


TOOL_SPEC = {
    "name": "financial_audit_log_reader",
    "description": "Read and filter entries from the financial audit log to track user actions, transaction events, and system changes for compliance monitoring and fraud investigation.",
    "category": "system",
    "domain": "finance",
    "risk_level": "read",
    "schema": {
    "type": "object",
    "properties": {
        "start_date": {
            "type": "string",
            "description": "Start of the time range for log entries (ISO 8601 format, e.g. 2025-01-01T00:00:00Z)",
            "format": "date-time"
        },
        "end_date": {
            "type": "string",
            "description": "End of the time range for log entries (ISO 8601 format, e.g. 2025-01-31T23:59:59Z)",
            "format": "date-time"
        },
        "log_level": {
            "type": "string",
            "enum": [
                "INFO",
                "WARN",
                "ERROR",
                "CRITICAL"
            ],
            "description": "Optional: Filter by severity level of the log entry"
        },
        "user_id": {
            "type": "string",
            "description": "Optional: Filter by the user who performed the action (e.g., user123, system)"
        },
        "event_type": {
            "type": "string",
            "enum": [
                "LOGIN",
                "LOGOUT",
                "TRANSACTION_CREATE",
                "TRANSACTION_UPDATE",
                "TRANSACTION_DELETE",
                "ACCOUNT_MODIFY",
                "REPORT_GENERATE",
                "SETTING_CHANGE",
                "SYSTEM_EVENT"
            ],
            "description": "Optional: Filter by type of event"
        },
        "max_results": {
            "type": "integer",
            "description": "Optional: Maximum number of log entries to return (1-1000, default 100)",
            "minimum": 1,
            "maximum": 1000
        },
        "search_text": {
            "type": "string",
            "description": "Optional: Free-text search within log message content"
        }
    },
    "required": [
        "start_date",
        "end_date"
    ]
},
}
