/** Stable human-facing help. Keep this independent from application startup. */
export function printHelp(write: (text: string) => void = (text) => console.log(text)): void {
	write(
		[
			"Kageko CLI",
			"",
			"Usage: kageko [options] [-p <prompt>]",
			"",
			"Headless agent execution:",
			"  -p, --prompt <text>     Run a prompt and exit",
			"      --provider <id>     LLM provider (openai, anthropic, faux, ...)",
			"      --model <id>        Model id",
			"      --permission <p>    manual | workspace | unrestricted",
			"      --interaction <m>   interactive | unattended",
			"      --session <id>      Resume an existing session for this prompt",
			"  -r, --resume [id]       Resume an id, or open the interactive session picker",
			"  -c, --continue          Continue the most recently updated workspace session",
			"      --cwd <path>        Workspace root (defaults to the current directory)",
			"      --output <format>   text | json | stream-json",
			"      --resume-on-checkpoint",
			"                          Auto-resume a checkpointed execution slice",
			"  -h, --help              Show this help",
			"",
			"Operational commands:",
			"  prompt <text>            Run a prompt (also accepts the options above)",
			"  session <action>         List and manage persisted sessions",
			"  config <action>          Read or update validated configuration",
			"  auth <action>            Store, inspect, or remove credentials",
			"  plugin <action>          Install or uninstall plugins",
			"  task <action>            Inspect or stop supervised task output",
			"  cron <action>            Manage scheduled prompts",
			"  capability list          Inspect session MCP/plugins/skills",
			"  memory <action>          Inspect, query, and grow session memory",
			"  learning <action>        Review learned items awaiting approval",
			"  goal <action>            Inspect and manage session goals",
			"  skill <action>           List, reload, or remove skills",
			"  mcp <action>             Manage MCP servers",
			"  trust <action>           Inspect, grant, or revoke workspace trust",
			"  setup                    Run the interactive provider/model setup wizard",
			"",
			"Without a command or --prompt, Kageko starts the interactive TUI.",
		].join("\n"),
	);
}
